grant select on ahmadmin.AssignedAdminUser to test_psa with grant option;
grant select on ahmadmin.AssignedTask to test_psa with grant option;
grant select on ahmadmin.BenefitProvisionLineValue to test_psa with grant option;
grant select on ahmadmin.CESettings to test_psa with grant option;
grant select on ahmadmin.CEInstructions to test_psa with grant option;
grant select on ahmadmin.CEMessagingSettings to test_psa with grant option;
grant select on ahmadmin.DMSettings to test_psa with grant option;
grant select on ahmadmin.FamilySupplierXref to test_psa with grant option;
grant select on ahmadmin.MAHSettings to test_psa with grant option;
grant select on ahmadmin.MasterSupplier to test_psa with grant option;
grant select on ahmadmin.MemberDirectedWellnessSettings to test_psa with grant option;
grant select on ahmadmin.PlanSponsor to test_psa with grant option;
grant select on ahmadmin.ProductBPLVXREF to test_psa with grant option;
grant select on ahmadmin.PurchasedProduct to test_psa with grant option;
grant select on ahmadmin.PurchasedProductOffering to test_psa with grant option;
grant select on ahmadmin.PurchasedProdSettngAttrValXREF to test_psa with grant option;
grant select on ahmadmin.PurchasedProductInstructions to test_psa with grant option;
grant select on ahmadmin.PurchasedProductCOMMSetup to test_psa with grant option;
grant select on ahmadmin.PurchasedProductTargetPln to test_psa with grant option;
grant select on ahmadmin.psa_segment_change_requests to test_psa with grant option;
grant select on ahmadmin.supplieracctpackagexref to test_psa with grant option;
grant select on ahmadmin.PurchasedProductSettings to test_psa with grant option;
grant select on ahmadmin.PurchasedProdOffngExtVendor to test_psa with grant option;
grant select on AHMADMIN.PurchasedProdOffngMaxReward to test_psa with grant option;
grant select on AHMADMIN.PurchasedProdOffngAttrValXREF to test_psa with grant option;
grant select on ahmadmin.psa_bpu_supplier_xref to test_psa with grant option;
grant select on ahmadmin.psa_bpu_supplier_xref to test_psa with grant option;
grant select on ahmadmin.Supplier to test_psa with grant option;
grant select on ahmadmin.SupplierGroup to test_psa with grant option;
grant select on ahmadmin.SupplierOrgRelation to test_psa with grant option;
grant select on ahmadmin.WorkFlowProcessInstance to test_psa with grant option;

grant select on ods.CEODSRunSync to test_psa with grant option;
grant select on ods.CSASupplierXREF to test_psa with grant option;
grant select on ods.CSASupplierXREFHist to test_psa with grant option;
grant select on ods.ETLMasterSupplierOverride to test_psa with grant option;
grant select on ods.InsuranceOrgSupplierRelation to test_psa with grant option;
grant select on ods.MasterSupplierSupplierRelation to test_psa with grant option;
grant select on ods.MasterSupplierOrganization to test_psa with grant option;
grant select on ods.InsuranceOrganization to test_psa with grant option;
grant select on ods.ProgramSuppressionProcess to test_psa with grant option;
grant select on ods.Supplier to test_psa with grant option;
grant select on ods.SupplierExtract to test_psa with grant option;
grant select on ods.SupplierPlansponsrRelationship to test_psa with grant option;
grant select on ods.SupplierProductFulfillment to test_psa with grant option;
grant select on ods.SupplierProductRelation to test_psa with grant option;
grant select on ods.SupplierProductSettings to test_psa with grant option; 
grant select on ods.SupplierProgramRelation to test_psa with grant option;
grant select on ods.SupplierCSAMoveInfo to test_psa with grant option;

grant execute on ahmadmin.pkg_product_setup_automation to test_psa with grant option;

grant select, update on ods.stg_suppliercontrol to test_psa with grant option;
grant select, update on ods.supplierbatch to test_psa with grant option;
