\echo Schemas/MEMBER_DATA/Tables/reference_codes.sql ...
\i Schemas/MEMBER_DATA/Tables/reference_codes.sql

\echo Schemas/MEMBER_DATA/Tables/loinc.sql ...
\i Schemas/MEMBER_DATA/Tables/loinc.sql

\echo Schemas/MEMBER_DATA/Tables/health_trackers.sql ...
\i Schemas/MEMBER_DATA/Tables/health_trackers.sql

\echo Schemas/MEMBER_DATA/Tables/health_tracker_elements.sql ...
\i Schemas/MEMBER_DATA/Tables/health_tracker_elements.sql

\echo Schemas/MEMBER_DATA/Tables/htrack_measurement_types.sql ...
\i Schemas/MEMBER_DATA/Tables/htrack_measurement_types.sql

\echo Schemas/MEMBER_DATA/Tables/htrack_element_measurement_xref.sql ...
\i Schemas/MEMBER_DATA/Tables/htrack_element_measurement_xref.sql

\echo Schemas/MEMBER_DATA/Tables/members.sql ...
\i Schemas/MEMBER_DATA/Tables/members.sql

\echo Schemas/MEMBER_DATA/Tables/patient_claims.sql ...
\i Schemas/MEMBER_DATA/Tables/patient_claims.sql

\echo Schemas/MEMBER_DATA/Tables/patient_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Tables/patient_diagnoses.sql

\echo Schemas/MEMBER_DATA/Tables/patient_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Tables/patient_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Tables/patient_prescriptions.sql ...
\i Schemas/MEMBER_DATA/Tables/patient_prescriptions.sql

\echo Schemas/MEMBER_DATA/Tables/lab_results.sql ...
\i Schemas/MEMBER_DATA/Tables/lab_results.sql

\echo Schemas/MEMBER_DATA/Tables/htrack_results.sql ...
\i Schemas/MEMBER_DATA/Tables/htrack_results.sql

\echo Schemas/MEMBER_DATA/Tables/pre_cert_insurance_cases.sql ...
\i Schemas/MEMBER_DATA/Tables/pre_cert_insurance_cases.sql

\echo Schemas/MEMBER_DATA/Tables/pre_cert_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Tables/pre_cert_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Tables/pre_cert_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Tables/pre_cert_diagnoses.sql

\echo Schemas/MEMBER_DATA/Tables/reported_drug_usage.sql ...
\i Schemas/MEMBER_DATA/Tables/reported_drug_usage.sql

\echo Schemas/MEMBER_DATA/Tables/hra_questions_answers.sql ...
\i Schemas/MEMBER_DATA/Tables/hra_questions_answers.sql

\echo Schemas/MEMBER_DATA/Tables/hra_member_survey_results.sql ...
\i Schemas/MEMBER_DATA/Tables/hra_member_survey_results.sql