set schema 'member_data';

\echo Schemas/MEMBER_DATA/Indexes_constraints/hra_questions_answers.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/hra_questions_answers.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/members.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/members.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/patient_claims.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/patient_claims.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/patient_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/patient_diagnoses.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/patient_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/patient_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/patient_prescriptions.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/patient_prescriptions.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/lab_results.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/lab_results.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/htrack_results.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/htrack_results.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_insurance_cases.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_insurance_cases.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_diagnoses.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/pre_cert_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/reported_drug_usage.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/reported_drug_usage.sql

\echo Schemas/MEMBER_DATA/Indexes_constraints/hra_member_survey_results.sql ...
\i Schemas/MEMBER_DATA/Indexes_constraints/hra_member_survey_results.sql