\echo Schemas/MEMBER_DATA/Partitions/members.sql ...
\i Schemas/MEMBER_DATA/Partitions/members.sql

\echo Schemas/MEMBER_DATA/Partitions/patient_claims.sql ...
\i Schemas/MEMBER_DATA/Partitions/patient_claims.sql

\echo Schemas/MEMBER_DATA/Partitions/patient_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Partitions/patient_diagnoses.sql

\echo Schemas/MEMBER_DATA/Partitions/patient_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Partitions/patient_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Partitions/patient_prescriptions.sql ...
\i Schemas/MEMBER_DATA/Partitions/patient_prescriptions.sql

\echo Schemas/MEMBER_DATA/Partitions/lab_results.sql ...
\i Schemas/MEMBER_DATA/Partitions/lab_results.sql

\echo Schemas/MEMBER_DATA/Partitions/htrack_results.sql ...
\i Schemas/MEMBER_DATA/Partitions/htrack_results.sql

\echo Schemas/MEMBER_DATA/Partitions/pre_cert_insurance_cases.sql ...
\i Schemas/MEMBER_DATA/Partitions/pre_cert_insurance_cases.sql

\echo Schemas/MEMBER_DATA/Partitions/pre_cert_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Partitions/pre_cert_diagnoses.sql

\echo Schemas/MEMBER_DATA/Partitions/pre_cert_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Partitions/pre_cert_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Partitions/reported_drug_usage.sql ...
\i Schemas/MEMBER_DATA/Partitions/reported_drug_usage.sql

\echo Schemas/MEMBER_DATA/Partitions/hra_member_survey_results.sql ...
\i Schemas/MEMBER_DATA/Partitions/hra_member_survey_results.sql