\echo Schemas/MEMBER_DATA/Types/typ_claim.sql ...
\i Schemas/MEMBER_DATA/Types/typ_claim.sql

\echo Schemas/MEMBER_DATA/Types/typ_lab_result.sql ...
\i Schemas/MEMBER_DATA/Types/typ_lab_result.sql

\echo Schemas/MEMBER_DATA/Types/typ_patient_diagnosis.sql ...
\i Schemas/MEMBER_DATA/Types/typ_patient_diagnosis.sql

\echo Schemas/MEMBER_DATA/Types/typ_patient_medical_procedure.sql ...
\i Schemas/MEMBER_DATA/Types/typ_patient_medical_procedure.sql

\echo Schemas/MEMBER_DATA/Types/typ_prescription.sql ...
\i Schemas/MEMBER_DATA/Types/typ_prescription.sql

\echo Schemas/MEMBER_DATA/Types/typ_pre_cert_diagnosis.sql ...
\i Schemas/MEMBER_DATA/Types/typ_pre_cert_diagnosis.sql

\echo Schemas/MEMBER_DATA/Types/typ_pre_cert_procedure.sql ...
\i Schemas/MEMBER_DATA/Types/typ_pre_cert_procedure.sql

\echo Schemas/MEMBER_DATA/Types/typ_pre_certification.sql ...
\i Schemas/MEMBER_DATA/Types/typ_pre_certification.sql

\echo Schemas/MEMBER_DATA/Types/typ_drug_usage.sql ...
\i Schemas/MEMBER_DATA/Types/typ_drug_usage.sql

\echo Schemas/MEMBER_DATA/Types/typ_hra_survey_response.sql ...
\i Schemas/MEMBER_DATA/Types/typ_hra_survey_response.sql

\echo Schemas/MEMBER_DATA/Types/typ_member_info.sql ...
\i Schemas/MEMBER_DATA/Types/typ_member_info.sql
