\echo Schemas/MEMBER_DATA/Views/v_claims.sql ...
\i Schemas/MEMBER_DATA/Views/v_claims.sql

\echo Schemas/MEMBER_DATA/Views/v_htrack_results.sql ...
\i Schemas/MEMBER_DATA/Views/v_htrack_results.sql

\echo Schemas/MEMBER_DATA/Views/v_lab_results.sql ...
\i Schemas/MEMBER_DATA/Views/v_lab_results.sql

\echo Schemas/MEMBER_DATA/Views/v_patient_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Views/v_patient_diagnoses.sql

\echo Schemas/MEMBER_DATA/Views/v_patient_medical_procedures.sql ...
\i Schemas/MEMBER_DATA/Views/v_patient_medical_procedures.sql

\echo Schemas/MEMBER_DATA/Views/v_prescriptions.sql ...
\i Schemas/MEMBER_DATA/Views/v_prescriptions.sql

\echo Schemas/MEMBER_DATA/Views/v_pre_cert_diagnoses.sql ...
\i Schemas/MEMBER_DATA/Views/v_pre_cert_diagnoses.sql

\echo Schemas/MEMBER_DATA/Views/v_pre_cert_procedures.sql ...
\i Schemas/MEMBER_DATA/Views/v_pre_cert_procedures.sql

\echo Schemas/MEMBER_DATA/Views/v_pre_certifications.sql ...
\i Schemas/MEMBER_DATA/Views/v_pre_certifications.sql

\echo Schemas/MEMBER_DATA/Views/v_hra_survey_results.sql ...
\i Schemas/MEMBER_DATA/Views/v_hra_survey_results.sql

\echo Schemas/MEMBER_DATA/Views/v_hra_htrack_results.sql ...
\i Schemas/MEMBER_DATA/Views/v_hra_htrack_results.sql

\echo Schemas/MEMBER_DATA/Views/v_reported_drug_usage.sql ...
\i Schemas/MEMBER_DATA/Views/v_reported_drug_usage.sql