CREATE OR REPLACE FUNCTION get_begin_date() RETURNS DATE
LANGUAGE PLPGSQL STABLE STRICT SECURITY DEFINER SET search_path TO 'member_data' AS $$
DECLARE
  ret DATE;
BEGIN
  ret := TO_DATE(CURRENT_SETTING('he.begin_date'), 'YYYY-MM-DD');

  RETURN CASE WHEN ret > DATE '0001-01-01' THEN ret ELSE DATE '0001-01-01' END;
EXCEPTION
 WHEN OTHERS THEN
  IF SQLSTATE = '42704' THEN -- Un-initialized setting
    RETURN DATE '0001-01-01';
  ELSE
    RAISE;
  END IF;
END $$;