DELETE FROM etladmin.cnf_data_flows WHERE data_flow_cd IN ('PSA_ARCHIVE_PERS_DATA', 'PSA_PROCESS_PERS_DATA');

INSERT INTO etladmin.cnf_data_flows tgt
(
  data_flow_cd, description,
  max_num_of_jobs, heartbeat_dt, last_proc_id, signal
)
SELECT 'PSA_ARCHIVE_PERS_DATA', 'Preserving the received PERS data', 4, SYSDATE, NULL, 'STOP' FROM dual UNION ALL
SELECT 'PSA_PROCESS_PERS_DATA', 'Processing Product Setup Automation data received from PERS', 4, SYSDATE, NULL, 'STOP' FROM dual;

INSERT INTO etladmin.cnf_data_flow_steps
(
  data_flow_cd, set_num, num, operation, tgt, src, match_cols, whr, hint, check_changed,
  generate, del, versions, err_table, commit_at, as_job
) 
SELECT-- DATA_FLOW_CD   SET NUM  OPER      TARGET                                     SOURCE                                      MATCH_COLS            WHERE                                  HINT   CHK_CHNG    GENERATE                                                                       DELETE         VERS  ERRT   CMT  AJ 
'PSA_ARCHIVE_PERS_DATA', 1,  1, 'INSERT',  'AHMADMIN.PSA_PERS_BATCHES',               'AHMADMIN.VW_PSA_PERS_BATCHES',             NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,   -1, 'N' FROM dual UNION ALL SELECT
'PSA_ARCHIVE_PERS_DATA', 1,  2, 'INSERT',  'AHMADMIN.PSA_PERS_DATA',                  'AHMADMIN.VW_PSA_PERS_DATA',                NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,   -1, 'N' FROM dual UNION ALL SELECT
-- Step set #1 - archival of the new PERS data:                                                                                                                                                                                                                                                                
'PSA_PROCESS_PERS_DATA', 1,  1, 'DELETE',  'AHMADMIN.PSA_PROCESS_RESULTS',            'AHMADMIN.VW_PSA_PROCESS_RESULTS_DELETE',   'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
-- Step set #2 - load of the new PERS data:                                                           
'PSA_PROCESS_PERS_DATA', 2,  1, 'MERGE',   'AHMADMIN.PLANSPONSOR',                    'AHMADMIN.VW_PSA_PLAN_SPONSOR',             'ROWID',              NULL,                                  NULL,  NULL,       'PlanSponsorSKEY=AHMADMIN.PlanSponsor_SEQ.NEXTVAL',                            NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  2, 'MERGE',   'AHMADMIN.PSA_CONTROLS',                   'AHMADMIN.VW_PSA_CONTROLS',                 'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT 
'PSA_PROCESS_PERS_DATA', 2,  3, 'MERGE',   'AHMADMIN.PSA_BENEFIT_PROVISION_UNITS',    'AHMADMIN.VW_PSA_BENEFIT_PROVISION_UNITS',  'ROWID',              NULL,                                  NULL,  NULL,       'bpu_skey=AHMADMIN.ControlSuffixAccount_SEQ.NEXTVAL',                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  4, 'UPDATE',  'AHMADMIN.PSA_BPU_BPLV_XREF',              'AHMADMIN.VW_PSA_TERMINATIONS',             'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  5, 'UPDATE',  'ODS.STG_SUPPLIERCONTROL',                 'AHMADMIN.VW_PSA_SEGM_CHNG_REQ',            NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  6, 'UPDATE',  'AHMADMIN.PSA_CONTROLS',                   'AHMADMIN.VW_PSA_SEGM_CHNG_REQ',            NULL,                 'status=''HONORED''',                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  7, 'UPDATE',  'AHMADMIN.PSA_SEGMENT_CHANGE_REQUESTS',    'AHMADMIN.VW_PSA_SEGM_CHNG_REQ',            'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  8, 'INSERT',  'AHMADMIN.TMP_PSA_BPU_BPLV_XREF',          'AHMADMIN.VW_PSA_BPU_BPLV_XREF',            NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2,  9, 'MERGE',   'AHMADMIN.PSA_BPU_BPLV_XREF',              'AHMADMIN.TMP_PSA_BPU_BPLV_XREF',           'ROWID',              'update_comment NOT LIKE ''IGNORE%''', NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2, 10, 'SQL',     'N/A', 'DELETE FROM ahmadmin.psa_bpu_bplv_xref WHERE end_dt <= start_dt;',             NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2, 11, 'INSERT',  'ODS.SUPPLIERERRORSUMMARY',                'AHMADMIN.TMP_PSA_BPU_BPLV_XREF',           NULL,                 'update_comment LIKE ''IGNORE%''',     NULL,  NULL,       'SupplierErrorSummarySKEY=ods.SupplierErrorSummary_SEQ.NEXTVAL',               NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 2, 12, 'INSERT',  'ODS.SUPPLIERERRORDETAIL',                 'AHMADMIN.VW_PSA_BPU_BPLV_IGNORE',          NULL,                 NULL,                                  NULL,  NULL,       'SupplierErrorDetailSKEY=SupplierErrorDetail_SEQ.NEXTVAL',                     NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
-- Step set #3 - Supplier and Purchased Product logic:                                                              
'PSA_PROCESS_PERS_DATA', 3,  1, 'INSERT',  'AHMADMIN.TMP_PSA_BPU_PRODUCTS',           'AHMADMIN.VW_PSA_BPU_PRODUCTS',             NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  2, 'INSERT',  'AHMADMIN.TMP_PSA_BPU_EVOLUTION',          'AHMADMIN.VW_PSA_BPU_EVOLUTION',            NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  3, 'DELETE',  'AHMADMIN.PSA_BPU_SUPPLIER_XREF',          'AHMADMIN.VW_PSA_2ND_BPU_SUPPLIER_XREF',    'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  4, 'INSERT',  'AHMADMIN.SUPPLIER',                       'AHMADMIN.VW_PSA_NEW_SUPPLIERS',            NULL,                 NULL,                                  NULL,  NULL,       'SupplierID,AHMSupplierID='||                           
                                                                                                                                                                                                                  'AHMADMIN.supplier_seq.NEXTVAL,AHMADMIN.master_supplier_seq.NEXTVAL',          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  5, 'MERGE',   'AHMADMIN.PSA_BPU_SUPPLIER_XREF',          'AHMADMIN.VW_PSA_BPU_SUPPLIER_XREF',        'ROWID',              NULL,                                  NULL,  NULL,       'insert_comment=psa.get_parameter(''USERID'')',                                NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  6, 'INSERT',  'AHMADMIN.TMP_PSA_SUPPLIER_PRODUCTS',      'AHMADMIN.VW_PSA_SUPPLIER_PRODUCTS',        NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  7, 'MERGE',   'AHMADMIN.PURCHASEDPRODUCT',               'AHMADMIN.VW_PSA_PURCHASED_PRODUCTS',       'ROWID',              NULL,                                  NULL,  NULL,       'PurchasedProductID=AHMADMIN.PurchasedProduct_SEQ.NEXTVAL',                    NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 3,  8, 'UPDATE',  'AHMADMIN.SUPPLIER',                       'AHMADMIN.VW_PSA_SUPPLIER_INFO',            'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
-- Step set #4 - Product Configuration:
'PSA_PROCESS_PERS_DATA', 4,  1, 'INSERT',  'AHMADMIN.PURCHASEDPRODUCTSETTINGS',       'AHMADMIN.VW_PSA_PPRD_SETTINGS',            NULL,                 NULL,                                  NULL,  NULL,       'PurchasedProductSettingsSKEY=AHMADMIN.PurchasedProductSettings_SEQ.NEXTVAL',  NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  2, 'INSERT',  'AHMADMIN.TMP_PSA_PPROD_OFFERING',         'AHMADMIN.VW_PSA_PPROD_OFFERING',           NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  3, 'MERGE',   'AHMADMIN.PURCHASEDPRODUCTOFFERING',       'AHMADMIN.TMP_PSA_PPROD_OFFERING',          'ROWID',              NULL,                                  NULL,  NULL,       'PurchasedproductOfferingSKEY=AHMADMIN.PurchasedProductOffering_seq.NEXTVAL',  NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  4, 'INSERT',  'AHMADMIN.MAHSETTINGS',                    'AHMADMIN.VW_PSA_MAHSETTINGS',              NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  5, 'INSERT',  'AHMADMIN.PURCHASEDPRODSETTNGATTRVALXREF', 'AHMADMIN.VW_PSA_PPRDSETTNG_ATTRVAL_XR',    NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  6, 'INSERT',  'AHMADMIN.DMSETTINGS',                     'AHMADMIN.VW_PSA_DMSETTINGS',               NULL,                 NULL,                                  NULL,  NULL,       'DMSettingsPPSSkey=AHMADMIN.DMSettings_seq.NEXTVAL',                           NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  7, 'INSERT',  'AHMADMIN.MEMBERDIRECTEDWELLNESSSETTINGS', 'AHMADMIN.VW_PSA_MMBRDRCT_WLNS_SETTINGS',   NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  8, 'INSERT',  'AHMADMIN.PURCHASEDPRODUCTTARGETPLN',      'AHMADMIN.VW_PSA_PPRD_TARGETPLN',           NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4,  9, 'INSERT',  'AHMADMIN.PURCHASEDPRODOFFNGATTRVALXREF',  'AHMADMIN.VW_PSA_PPRDOFFNG_ATTRVAL_XR',     NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 10, 'INSERT',  'AHMADMIN.PURCHASEDPRODOFFNGEXTVENDOR',    'AHMADMIN.VW_PSA_PPRDOFFNG_EXTVENDOR',      NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 11, 'INSERT',  'AHMADMIN.PURCHASEDPRODOFFNGMAXREWARD',    'AHMADMIN.VW_PSA_PPRDOFFNG_MAXREWARD',      NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 12, 'INSERT',  'AHMADMIN.CESETTINGS',                     'AHMADMIN.VW_PSA_CESETTINGS',               NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 13, 'INSERT',  'AHMADMIN.CEINSTRUCTIONS',                 'AHMADMIN.VW_PSA_CEINSTRUCTIONS',           NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 14, 'INSERT',  'AHMADMIN.CEMESSAGINGSETTINGS',            'AHMADMIN.VW_PSA_CEMSGSETTINGS',            NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 15, 'INSERT',  'AHMADMIN.PURCHASEDPRODUCTINSTRUCTIONS',   'AHMADMIN.VW_PSA_PPRODINSTRUCTIONS',        NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 16, 'MERGE',   'AHMADMIN.FAMILYSUPPLIERXREF',             'AHMADMIN.VW_PSA_FAMILYSUPPLIER_XR',        'SupplierID',         NULL,                                  NULL,  'FamilyID', NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 17, 'INSERT',  'AHMADMIN.TMP_PSA_SUPPLIERACCTPKG_XR',     'AHMADMIN.VW_PSA_SUPPLIERACCTPKG_XR',       NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 18, 'MERGE',   'AHMADMIN.SUPPLIERACCTPACKAGEXREF',        'AHMADMIN.TMP_PSA_SUPPLIERACCTPKG_XR',      'ROWID',              NULL,                                  NULL,  NULL,       'SupplierAcctPackageXrefSKEY=AHMADMIN.SupplierAcctPackageXref_seq.NEXTVAL',    'if notfound', NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 19, 'INSERT',  'AHMADMIN.TMP_PSA_PPROD_COMMSETUP',        'AHMADMIN.VW_PSA_PPROD_COMMSETUP',          NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 20, 'MERGE',   'AHMADMIN.PURCHASEDPRODUCTCOMMSETUP',      'AHMADMIN.TMP_PSA_PPROD_COMMSETUP',         'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          'if notfound', NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 21, 'INSERT',  'AHMADMIN.SUPPLIERGROUP',                  'AHMADMIN.VW_PSA_SUPPLIERGROUP',            NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 22, 'INSERT',  'AHMADMIN.SUPPLIERORGRELATION',            'AHMADMIN.VW_PSA_SUPPORGRELATION',          NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 23, 'INSERT',  'AHMADMIN.WORKFLOWPROCESSINSTANCE',        'AHMADMIN.VW_PSA_WFP_INSTANCES',            NULL,                 's.WorkFlowProcessInstanceID IS NULL', NULL,  NULL,       'WorkFlowProcessInstanceID=AHMADMIN.wfpinstanceseq.NEXTVAL',                   NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 24, 'INSERT',  'AHMADMIN.ASSIGNEDTASK',                   'AHMADMIN.VW_PSA_ASSIGNED_TASKS',           NULL,                 's.AssignedTaskID IS NULL',            NULL,  NULL,       'AssignedTaskID=AHMADMIN.taskseq.NEXTVAL',                                     NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 25, 'INSERT',  'AHMADMIN.ASSIGNEDADMINUSER',              'AHMADMIN.VW_PSA_ASSIGNED_ADMIN_USERS',     NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 4, 26, 'UPDATE',  'AHMADMIN.PURCHASEDPRODUCT',               'AHMADMIN.VW_PSA_PPROD_SETTING_STATUS',     'PurchasedProductID', NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
-- Step set #5 - Synchronization AHMADMIN -> ODS:                             
'PSA_PROCESS_PERS_DATA', 5,  1, 'MERGE',   'ODS.PLANSPONSOR',                         'AHMADMIN.VW_PSA_ODS_PLAN_SPONSOR',         'ROWID',              NULL,                                  NULL,  NULL,       'PlanSponsorInstanceID=ods.ods_plansponsor_seq.NEXTVAL',                       NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  2, 'MERGE',   'ODS.MASTERSUPPLIERORGANIZATION',          'AHMADMIN.VW_PSA_ODS_MASTER_SUPPLIERS',     'ROWID',              NULL,                                  NULL,  NULL,       'MasterSupplierOrgID=ods.ods_party_seq.NEXTVAL',                               NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  3, 'MERGE',   'ODS.ETLMASTERSUPPLIEROVERRIDE',           'AHMADMIN.VW_PSA_ODS_ETLMASTERSUPPL_OVRD',  'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  4, 'MERGE',   'ODS.INSURANCEORGANIZATION',               'AHMADMIN.VW_PSA_ODS_INS_ORGANIZATION',     'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  5, 'INSERT',  'ODS.PROGRAMSUPPRESSIONPROCESS',           'AHMADMIN.VW_PSA_ODS_PRGM_SUPPR_PROCESS',   NULL,                 NULL,                                  NULL,  NULL,       'ProgramSuppressionProcesssKEY=ODS.ProgramSuppressionProcesss_seq.NEXTVAL',    NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  6, 'MERGE',   'ODS.SUPPLIERORGANIZATION',                'AHMADMIN.VW_PSA_ODS_SUPPL_ORGANIZATION',   'AHMSupplierID',      NULL,                                  NULL,  NULL,       'SupplierOrgID=ODS.ods_party_seq.NEXTVAL',                                     NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  7, 'MERGE',   'ODS.SUPPLIERPLANSPONSRRELATIONSHIP',      'AHMADMIN.VW_PSA_ODS_SUPPLPLANSPONSORREL',  'ROWID',              NULL,                                  NULL,  NULL,       'SupplierPlansponsorSkey=ODS.ods_supplierplansp_seq.NEXTVAL',                  NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  8, 'MERGE',   'ODS.MASTERSUPPLIERSUPPLIERRELATION',      'AHMADMIN.VW_PSA_ODS_MSTRSUPPL_SUPPL_REL',  'SupplierID',         NULL,                                  NULL,  NULL,       'MstrSupplierSupplierSKEY=ODS.ods_dim_seq.NEXTVAL',                            NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5,  9, 'MERGE',   'ODS.INSURANCEORGSUPPLIERRELATION',        'AHMADMIN.VW_PSA_ODS_INSORG_SUPPLIER_REL',  'ROWID',              NULL,                                  NULL,  NULL,       'InsuranceOrgSupplierSKEY=ODS.ods_dim_seq.NEXTVAL',                            NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 10, 'MERGE',   'ODS.SUPPLIERPRODUCTRELATION',             'AHMADMIN.VW_PSA_ODS_SUPPLIER_PROD_RELN',   'ROWID',              NULL,                                  NULL,  NULL,       'SupplierProductRelSKEY=ODS.ods_supplierproduct_seq.NEXTVAL',                  NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 11, 'UPDATE',  'ODS.SUPPLIERORGANIZATION',                'AHMADMIN.VW_PSA_ODS_SUPPLORG_PRODSTATUS',  'AHMSupplierID',      NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 12, 'MERGE',   'ODS.SUPPLIERPROGRAMRELATION',             'AHMADMIN.VW_PSA_ODS_SUPPLIER_PRGRM_RELN',  'ROWID',              NULL,                                  NULL,  NULL,       'SupplierProgramRelationID=ODS.SupplierProgramRelation_seq.NEXTVAL',           NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 13, 'MERGE',   'ODS.SUPPLIERPRODUCTSETTINGS',             'AHMADMIN.VW_PSA_ODS_SUPPLIER_PROD_STNGS',  'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 14, 'MERGE',   'ODS.CSASUPPLIERXREF',                     'AHMADMIN.VW_PSA_ODS_CSASUPPLIERXREF',      'ROWID',              NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 15, 'INSERT',  'ODS.CSASUPPLIERXREFHIST',                 'AHMADMIN.VW_PSA_ODS_CSASUPPLIERXREFHIST',  NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 16, 'INSERT',  'ODS.CEODSRUNSYNC',                        'AHMADMIN.VW_PSA_ODS_MASTER_SUPPLIERS',     NULL,                 'row_id IS NULL',                      NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 17, 'MERGE',   'ODS.SUPPLIERMANAGEMENT',                  'AHMADMIN.VW_PSA_ODS_SUPPLIER_MANAGEMENT',  'ROWID',              NULL,                                  NULL,  NULL,       'SupplierManagementSKey=ODS.ods_suppliermanage_seq.NEXTVAL',                   NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 18, 'MERGE',   'ODS.SUPPLIERPRODUCTFULFILLMENT',          'AHMADMIN.VW_PSA_ODS_SUPPLPRDFULFILLMENT',  'ROWID',              NULL,                                  NULL,  NULL,       'SupplierProductFulfillSkey=ODS.supplierprodrelfulfillment_seq.NEXTVAL',       NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 19, 'INSERT',  'ODS.SUPPLIERCSAMOVEINFO',                 'AHMADMIN.VW_PSA_ODS_SUPPLIERCSAMOVEINFO',  NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 20, 'INSERT',  'ODS.SUPPLIEREXTRACT',                     'AHMADMIN.VW_PSA_ODS_SUPPLIEREXTRACT',      NULL,                 NULL,                                  NULL,  NULL,       'SupplierExtractSKey=ODS.supplierextract_seq.NEXTVAL',                         NULL,          NULL, NULL,    0, 'N' FROM dual UNION ALL SELECT
'PSA_PROCESS_PERS_DATA', 5, 21, 'INSERT',  'AHMADMIN.PSA_PROCESS_RESULTS',            'AHMADMIN.VW_PSA_PROCESS_RESULTS',          NULL,                 NULL,                                  NULL,  NULL,       NULL,                                                                          NULL,          NULL, NULL,    0, 'N' FROM dual;

COMMIT;